site_name: Anilist-Manga-Updater
site_url: https://rlalpha49.github.io/Anilist-Manga-Updater
site_description: A python application that updates your Anilist manga list from Kenmei.
site_author: RLAlpha49
repo_url: https://github.com/RLAlpha49/Anilist-Manga-Updater
repo_name: RLAlpha49/AniLinkPy
copyright: >
  Copyright &copy; 2024 RLAlpha49 under the MIT License –
  <a href="#__consent">Change cookie settings</a>
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RLAlpha49
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/251479989378220044
  analytics:
    provider: google
    property:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
      - manage
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            heading_level: 3
            show_if_no_docstring: true
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_signatures: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            docstring_options:
              ignore_init_summary: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - git-committers:
      repository: RLAlpha49/Anilist-Manga-Updater
      branch: master

nav:
  - Home: index.md
  - Installation: installation.md
  - Anilist-Manga-Updater:
      - API:
          - AccessAPI: API/AccessAPI.md
          - APIRequests: API/APIRequests.md
          - GetAccessToken: API/GetAccessToken.md
          - Queries: API/Queries.md
          - UpdateManga: API/UpdateManga.md
      - Main:
          - GUI: Main/GUI.md
          - Program: Main/Program.md
      - Manga:
          - GetID: Manga/GetID.md
          - MangaSearch: Manga/MangaSearch.md
      - Utils:
          - Cache: Utils/Cache.md
          - Config: Utils/Config.md
          - Dictionaries: Utils/Dictionaries.md
          - GetFromFile: Utils/GetFromFile.md
          - Log: Utils/Log.md
          - WriteToFile: Utils/WriteToFile.md

theme:
  name: material
  font:
    text: Fira Sans
    code: Fira Code
  icon:
    repo: fontawesome/brands/git-alt
    annotation: material/plus-circle
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.top
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - content.action.view
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - attr_list
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - tables
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html