[tool.poetry]
name = "Anilist-Manga-Updater"
version = "1.72"
description = "Syncs your Kenmei exported manga list with AniList"
authors = ["RLAlpha49 <75044176+RLAlpha49@users.noreply.github.com>"]
readme = "README.md"
license = "GNU General Public License v3.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
Pillow = "^10.3.0"
customtkinter = "^5.2.2"
CTkToolTip = "^0.8"
requests = "^2.32.3"
pymoe = "^2.2"
pandas = "^2.2.2"
ruff = "^0.4.9"

[tool.poetry.dev-dependencies]
types-requests = "^2.32.0.20240602"
mypy = "^1.10.0"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.26"
mkdocstrings = {extras = ["crystal", "python"], version = "^0.25.1"}
mkdocs-git-revision-date-localized-plugin = "^1.2.6"
mkdocs-git-committers-plugin-2 = "^2.3.0"

[tool.ruff]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
disable_error_code = "attr-defined"