[tool.poetry]
name = "Anilist-Manga-Updater"
version = "1.72"
description = "Syncs your Kenmei exported manga list with AniList"
authors = ["RLAlpha49 <75044176+RLAlpha49@users.noreply.github.com>"]
readme = "README.md"
license = "GNU General Public License v3.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
Pillow = "^10.3.0"
customtkinter = "^5.2.2"
CTkToolTip = "^0.8"
requests = "^2.32.2"
pymoe = "^2.2"
pandas = "^2.2.2"

[tool.poetry.dev-dependencies]
types-requests = "^2.32.0.20240521"
isort = "^5.13.2"
black = "^24.4.2"
pylint = "^3.2.2"
mypy = "^1.10.0"
flake8 = "^7.0.0"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.24"
mkdocstrings = {extras = ["crystal", "python"], version = "^0.25.1"}
mkdocs-git-revision-date-localized-plugin = "^1.2.5"
mkdocs-git-committers-plugin-2 = "^2.3.0"

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.flake8]
max-line-length = 120

[tool.pylint]
max-line-length = 120
disable = "too-few-public-methods,missing-module-docstring,invalid-name,R0801"

[tool.mypy]
ignore_missing_imports = true
disable_error_code = "attr-defined"