name: Auto merge Dependabot PRs

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Ruff'
      - 'CodeQL'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
