name: Build Electron App

on:
  push:
    branches: [electron]
  pull_request:
    branches: [electron]

jobs:
  build-windows:
    name: Build Windows Artifacts
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run make
      - name: Upload Windows Build Artifacts (.exe and .msi)
        if: ${{ (github.event_name == 'push' && github.event.head_commit.id == github.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha == github.sha) }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            out/make/squirrel.windows/x64/Spotify-Skip-Tracker-Setup.exe
            out/make/squirrel.windows/x64/Spotify-Skip-Tracker-Setup.msi

  build-macos:
    name: Build macOS Artifacts
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run make
      - name: Upload macOS Build Artifacts
        if: ${{ (github.event_name == 'push' && github.event.head_commit.id == github.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha == github.sha) }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            out/make/Spotify-Skip-Tracker.dmg
            out/make/zip/darwin/arm64/Spotify Skip Tracker-darwin-arm64-1.0.0.zip

  build-linux:
    name: Build Linux Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run make
      - name: Upload Linux Build Artifacts
        if: ${{ (github.event_name == 'push' && github.event.head_commit.id == github.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha == github.sha) }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            out/make/deb/x64/spotify-skip-tracker_1.0.0_amd64.deb
