name: Generate Documentation

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    name: Build and Push Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Generate TypeDoc Documentation
        run: npm run docs

      - name: Deploy to Documentation Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: documentation
          clean: true
